// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package domain

import (
	"sync"
)

var (
	lockPermissionServiceMockAddScope   sync.RWMutex
	lockPermissionServiceMockValidScope sync.RWMutex
)

// PermissionServiceMock is a mock implementation of PermissionService.
//
//     func TestSomethingThatUsesPermissionService(t *testing.T) {
//
//         // make and configure a mocked PermissionService
//         mockedPermissionService := &PermissionServiceMock{
//             AddScopeFunc: func(userID uint64, ResouceID uint64, class ResourceClass, scope Scope) error {
// 	               panic("TODO: mock out the AddScope method")
//             },
//             ValidScopeFunc: func(userID uint64, ResourceID uint64, class ResourceClass, scope Scope) (bool, error) {
// 	               panic("TODO: mock out the ValidScope method")
//             },
//         }
//
//         // TODO: use mockedPermissionService in code that requires PermissionService
//         //       and then make assertions.
//
//     }
type PermissionServiceMock struct {
	// AddScopeFunc mocks the AddScope method.
	AddScopeFunc func(userID uint64, ResouceID uint64, class ResourceClass, scope Scope) error

	// ValidScopeFunc mocks the ValidScope method.
	ValidScopeFunc func(userID uint64, ResourceID uint64, class ResourceClass, scope Scope) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// AddScope holds details about calls to the AddScope method.
		AddScope []struct {
			// UserID is the userID argument value.
			UserID uint64
			// ResouceID is the ResouceID argument value.
			ResouceID uint64
			// Class is the class argument value.
			Class ResourceClass
			// Scope is the scope argument value.
			Scope Scope
		}
		// ValidScope holds details about calls to the ValidScope method.
		ValidScope []struct {
			// UserID is the userID argument value.
			UserID uint64
			// ResourceID is the ResourceID argument value.
			ResourceID uint64
			// Class is the class argument value.
			Class ResourceClass
			// Scope is the scope argument value.
			Scope Scope
		}
	}
}

// AddScope calls AddScopeFunc.
func (mock *PermissionServiceMock) AddScope(userID uint64, ResouceID uint64, class ResourceClass, scope Scope) error {
	if mock.AddScopeFunc == nil {
		panic("PermissionServiceMock.AddScopeFunc: method is nil but PermissionService.AddScope was just called")
	}
	callInfo := struct {
		UserID    uint64
		ResouceID uint64
		Class     ResourceClass
		Scope     Scope
	}{
		UserID:    userID,
		ResouceID: ResouceID,
		Class:     class,
		Scope:     scope,
	}
	lockPermissionServiceMockAddScope.Lock()
	mock.calls.AddScope = append(mock.calls.AddScope, callInfo)
	lockPermissionServiceMockAddScope.Unlock()
	return mock.AddScopeFunc(userID, ResouceID, class, scope)
}

// AddScopeCalls gets all the calls that were made to AddScope.
// Check the length with:
//     len(mockedPermissionService.AddScopeCalls())
func (mock *PermissionServiceMock) AddScopeCalls() []struct {
	UserID    uint64
	ResouceID uint64
	Class     ResourceClass
	Scope     Scope
} {
	var calls []struct {
		UserID    uint64
		ResouceID uint64
		Class     ResourceClass
		Scope     Scope
	}
	lockPermissionServiceMockAddScope.RLock()
	calls = mock.calls.AddScope
	lockPermissionServiceMockAddScope.RUnlock()
	return calls
}

// ValidScope calls ValidScopeFunc.
func (mock *PermissionServiceMock) ValidScope(userID uint64, ResourceID uint64, class ResourceClass, scope Scope) (bool, error) {
	if mock.ValidScopeFunc == nil {
		panic("PermissionServiceMock.ValidScopeFunc: method is nil but PermissionService.ValidScope was just called")
	}
	callInfo := struct {
		UserID     uint64
		ResourceID uint64
		Class      ResourceClass
		Scope      Scope
	}{
		UserID:     userID,
		ResourceID: ResourceID,
		Class:      class,
		Scope:      scope,
	}
	lockPermissionServiceMockValidScope.Lock()
	mock.calls.ValidScope = append(mock.calls.ValidScope, callInfo)
	lockPermissionServiceMockValidScope.Unlock()
	return mock.ValidScopeFunc(userID, ResourceID, class, scope)
}

// ValidScopeCalls gets all the calls that were made to ValidScope.
// Check the length with:
//     len(mockedPermissionService.ValidScopeCalls())
func (mock *PermissionServiceMock) ValidScopeCalls() []struct {
	UserID     uint64
	ResourceID uint64
	Class      ResourceClass
	Scope      Scope
} {
	var calls []struct {
		UserID     uint64
		ResourceID uint64
		Class      ResourceClass
		Scope      Scope
	}
	lockPermissionServiceMockValidScope.RLock()
	calls = mock.calls.ValidScope
	lockPermissionServiceMockValidScope.RUnlock()
	return calls
}
