// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package domain

import (
	"sync"
)

var (
	lockTagServiceMockCreateTag    sync.RWMutex
	lockTagServiceMockImagesForTag sync.RWMutex
	lockTagServiceMockTagByID      sync.RWMutex
	lockTagServiceMockTagImage     sync.RWMutex
	lockTagServiceMockUnTagImage   sync.RWMutex
)

// TagServiceMock is a mock implementation of TagService.
//
//     func TestSomethingThatUsesTagService(t *testing.T) {
//
//         // make and configure a mocked TagService
//         mockedTagService := &TagServiceMock{
//             CreateTagFunc: func(id string) error {
// 	               panic("TODO: mock out the CreateTag method")
//             },
//             ImagesForTagFunc: func(id string) (*[]Image, error) {
// 	               panic("TODO: mock out the ImagesForTag method")
//             },
//             TagByIDFunc: func(id string) (*Tag, error) {
// 	               panic("TODO: mock out the TagByID method")
//             },
//             TagImageFunc: func(id string, imageID uint64) error {
// 	               panic("TODO: mock out the TagImage method")
//             },
//             UnTagImageFunc: func(id string, imageID uint64) error {
// 	               panic("TODO: mock out the UnTagImage method")
//             },
//         }
//
//         // TODO: use mockedTagService in code that requires TagService
//         //       and then make assertions.
//
//     }
type TagServiceMock struct {
	// CreateTagFunc mocks the CreateTag method.
	CreateTagFunc func(id string) error

	// ImagesForTagFunc mocks the ImagesForTag method.
	ImagesForTagFunc func(id string) (*[]Image, error)

	// TagByIDFunc mocks the TagByID method.
	TagByIDFunc func(id string) (*Tag, error)

	// TagImageFunc mocks the TagImage method.
	TagImageFunc func(id string, imageID uint64) error

	// UnTagImageFunc mocks the UnTagImage method.
	UnTagImageFunc func(id string, imageID uint64) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateTag holds details about calls to the CreateTag method.
		CreateTag []struct {
			// ID is the id argument value.
			ID string
		}
		// ImagesForTag holds details about calls to the ImagesForTag method.
		ImagesForTag []struct {
			// ID is the id argument value.
			ID string
		}
		// TagByID holds details about calls to the TagByID method.
		TagByID []struct {
			// ID is the id argument value.
			ID string
		}
		// TagImage holds details about calls to the TagImage method.
		TagImage []struct {
			// ID is the id argument value.
			ID string
			// ImageID is the imageID argument value.
			ImageID uint64
		}
		// UnTagImage holds details about calls to the UnTagImage method.
		UnTagImage []struct {
			// ID is the id argument value.
			ID string
			// ImageID is the imageID argument value.
			ImageID uint64
		}
	}
}

// CreateTag calls CreateTagFunc.
func (mock *TagServiceMock) CreateTag(id string) error {
	if mock.CreateTagFunc == nil {
		panic("TagServiceMock.CreateTagFunc: method is nil but TagService.CreateTag was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	lockTagServiceMockCreateTag.Lock()
	mock.calls.CreateTag = append(mock.calls.CreateTag, callInfo)
	lockTagServiceMockCreateTag.Unlock()
	return mock.CreateTagFunc(id)
}

// CreateTagCalls gets all the calls that were made to CreateTag.
// Check the length with:
//     len(mockedTagService.CreateTagCalls())
func (mock *TagServiceMock) CreateTagCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	lockTagServiceMockCreateTag.RLock()
	calls = mock.calls.CreateTag
	lockTagServiceMockCreateTag.RUnlock()
	return calls
}

// ImagesForTag calls ImagesForTagFunc.
func (mock *TagServiceMock) ImagesForTag(id string) (*[]Image, error) {
	if mock.ImagesForTagFunc == nil {
		panic("TagServiceMock.ImagesForTagFunc: method is nil but TagService.ImagesForTag was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	lockTagServiceMockImagesForTag.Lock()
	mock.calls.ImagesForTag = append(mock.calls.ImagesForTag, callInfo)
	lockTagServiceMockImagesForTag.Unlock()
	return mock.ImagesForTagFunc(id)
}

// ImagesForTagCalls gets all the calls that were made to ImagesForTag.
// Check the length with:
//     len(mockedTagService.ImagesForTagCalls())
func (mock *TagServiceMock) ImagesForTagCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	lockTagServiceMockImagesForTag.RLock()
	calls = mock.calls.ImagesForTag
	lockTagServiceMockImagesForTag.RUnlock()
	return calls
}

// TagByID calls TagByIDFunc.
func (mock *TagServiceMock) TagByID(id string) (*Tag, error) {
	if mock.TagByIDFunc == nil {
		panic("TagServiceMock.TagByIDFunc: method is nil but TagService.TagByID was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	lockTagServiceMockTagByID.Lock()
	mock.calls.TagByID = append(mock.calls.TagByID, callInfo)
	lockTagServiceMockTagByID.Unlock()
	return mock.TagByIDFunc(id)
}

// TagByIDCalls gets all the calls that were made to TagByID.
// Check the length with:
//     len(mockedTagService.TagByIDCalls())
func (mock *TagServiceMock) TagByIDCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	lockTagServiceMockTagByID.RLock()
	calls = mock.calls.TagByID
	lockTagServiceMockTagByID.RUnlock()
	return calls
}

// TagImage calls TagImageFunc.
func (mock *TagServiceMock) TagImage(id string, imageID uint64) error {
	if mock.TagImageFunc == nil {
		panic("TagServiceMock.TagImageFunc: method is nil but TagService.TagImage was just called")
	}
	callInfo := struct {
		ID      string
		ImageID uint64
	}{
		ID:      id,
		ImageID: imageID,
	}
	lockTagServiceMockTagImage.Lock()
	mock.calls.TagImage = append(mock.calls.TagImage, callInfo)
	lockTagServiceMockTagImage.Unlock()
	return mock.TagImageFunc(id, imageID)
}

// TagImageCalls gets all the calls that were made to TagImage.
// Check the length with:
//     len(mockedTagService.TagImageCalls())
func (mock *TagServiceMock) TagImageCalls() []struct {
	ID      string
	ImageID uint64
} {
	var calls []struct {
		ID      string
		ImageID uint64
	}
	lockTagServiceMockTagImage.RLock()
	calls = mock.calls.TagImage
	lockTagServiceMockTagImage.RUnlock()
	return calls
}

// UnTagImage calls UnTagImageFunc.
func (mock *TagServiceMock) UnTagImage(id string, imageID uint64) error {
	if mock.UnTagImageFunc == nil {
		panic("TagServiceMock.UnTagImageFunc: method is nil but TagService.UnTagImage was just called")
	}
	callInfo := struct {
		ID      string
		ImageID uint64
	}{
		ID:      id,
		ImageID: imageID,
	}
	lockTagServiceMockUnTagImage.Lock()
	mock.calls.UnTagImage = append(mock.calls.UnTagImage, callInfo)
	lockTagServiceMockUnTagImage.Unlock()
	return mock.UnTagImageFunc(id, imageID)
}

// UnTagImageCalls gets all the calls that were made to UnTagImage.
// Check the length with:
//     len(mockedTagService.UnTagImageCalls())
func (mock *TagServiceMock) UnTagImageCalls() []struct {
	ID      string
	ImageID uint64
} {
	var calls []struct {
		ID      string
		ImageID uint64
	}
	lockTagServiceMockUnTagImage.RLock()
	calls = mock.calls.UnTagImage
	lockTagServiceMockUnTagImage.RUnlock()
	return calls
}
