development:
    dialect: postgres
    datasource: dbname=fokal sslmode=disable
    dir: migrations
    table: migrations

production:
    dialect: postgres
    datasource: ${DATBASE}
    dir: migrations
    table: migrations